# Generated by Django 4.2.3 on 2023-08-06 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_info_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='info',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.info'),
            preserve_default=False,
        ),
    ]
