# Generated by Django 4.2.3 on 2023-08-06 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_info_patient_patient_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='info',
        ),
        migrations.AddField(
            model_name='info',
            name='patient',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
            preserve_default=False,
        ),
    ]
