# Generated by Django 4.2.3 on 2023-08-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_visitereprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitereprise',
            name='Inapte',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
