# Generated by Django 4.2.3 on 2023-08-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_visitereprise_inapte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitereprise',
            name='Inapte',
        ),
        migrations.RemoveField(
            model_name='visitereprise',
            name='apte',
        ),
        migrations.AddField(
            model_name='visitereprise',
            name='choix',
            field=models.CharField(choices=[('apte', 'Apte'), ('Inapte', 'Inapte')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
