# Generated by Django 4.2.3 on 2023-08-13 23:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_visitereprise_inapte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitereprise',
            name='choix',
            field=models.CharField(choices=[('apte', "L'employé est apte à reprendre son travail"), ('Inapte_t', "L'employé est Inapte temporairement à reprendre son travail"), ('Inapte_d', "L'employé est Inapte définitivement à reprendre son travail")], max_length=10),
        ),
        migrations.AlterField(
            model_name='visitereprise',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='VisiteMedicaleSpontanee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visite', models.DateField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tension_arterielle', models.CharField(max_length=20)),
                ('symptomes', models.TextField()),
                ('observations', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
