# Generated by Django 4.2.3 on 2023-08-14 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_visitereprise_choix_alter_visitereprise_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systematique',
            name='patient',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
            preserve_default=False,
        ),
    ]
