# Generated by Django 4.2.3 on 2023-08-14 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_systematique_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systematique',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
    ]
