# Generated by Django 4.2.3 on 2023-08-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_systematique_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analyse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='systematique',
            name='analyses',
            field=models.ManyToManyField(blank=True, to='app.analyse'),
        ),
    ]
