# Generated by Django 4.2.3 on 2023-08-20 11:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_systematique_analyses'),
    ]

    operations = [
        migrations.CreateModel(
            name='surveillance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('taille', models.DecimalField(decimal_places=4, max_digits=4)),
                ('poids', models.DecimalField(decimal_places=4, max_digits=4)),
                ('T_A', models.DecimalField(decimal_places=4, max_digits=4)),
                ('A_V', models.DecimalField(decimal_places=4, max_digits=4)),
                ('pouls', models.DecimalField(decimal_places=4, max_digits=4)),
                ('Glycemie', models.DecimalField(decimal_places=4, max_digits=4)),
                ('Albumin', models.DecimalField(decimal_places=4, max_digits=4)),
                ('Glucose', models.DecimalField(decimal_places=4, max_digits=4)),
                ('Medecin_de_travail', models.CharField(max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.patient')),
            ],
        ),
    ]
