# Generated by Django 4.2.3 on 2023-08-20 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_surveillance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveillance',
            name='A_V',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='surveillance',
            name='Albumin',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='surveillance',
            name='Glucose',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='surveillance',
            name='Glycemie',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='surveillance',
            name='T_A',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='surveillance',
            name='poids',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='surveillance',
            name='pouls',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='surveillance',
            name='taille',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
