# Generated by Django 4.2.3 on 2023-08-20 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_laboratoire_analyse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratoire',
            name='analyse',
        ),
    ]
